Update _widget_reader.py
data-exp-lab/yt-napari pull request #108
Opened 2023-11-07 12:00 UTC by TomasPetro

I've edited it and it should work (I've tested saving the data and then loading it from File->OpenFile).  I did this for YtReader and TimeSeriesReader. But the validate_data_model function does not return the model only the JSON. I don't know if it bothers or not but I had a problem converting the returned model to JSON. Besides, there is a hardcoded $schema$ because without it I couldn't load JSON files and I didn't know where I could get it into the function.

2023-11-07 16:10 UTC, chrishavlin commented
Thanks, @TomasPetro ! I should have time to look this over later in the week.

2023-11-07 16:54 UTC, chrishavlin requested changes
I was trying to figure out why the tests are stalling -- it's cause you added the QApplication instances. Napari handles all the main QT context, these need to be removed.

2023-11-07 16:54 UTC, chrishavlin commented on src/yt_napari/_widget_reader.py
> +    app = QApplication(sys.argv)
These lines shouldn't be added -- napari takes care of all QT application and context handling and are why tests are stalling.
```suggestion
```

2023-11-07 16:54 UTC, chrishavlin commented on src/yt_napari/_widget_reader.py
> +    app.exec_()
```suggestion
```

2023-11-07 16:54 UTC, chrishavlin commented on src/yt_napari/_widget_reader.py
> +    app = QApplication(sys.argv)
```suggestion
```

2023-11-07 16:54 UTC, chrishavlin commented on src/yt_napari/_widget_reader.py
> +    app.exec_()
```suggestion
```

2023-11-07 16:56 UTC, chrishavlin commented
also, if you type `pre-commit.ci autofix` on it's own in a comment then the pre-commit bot will try to fix the failing style checks.

2023-11-07 21:46 UTC, TomasPetro commented
I looked at those comments and yes they were unnecessary features. I don't know why I put them there. I deleted them and tried them on my pc and everything went as before.

2023-11-10 16:19 UTC, chrishavlin requested changes
Thanks for the nice work, @TomasPetro ! 

I left some comments with some small changes to how you're setting the `"$schema"` entry. 

You'll also need to fix the failing style checks and add a new test.

**style checks**: you can read the full log here https://results.pre-commit.ci/run/github/448138442/1699393334.AOajljEzRPyJ5O8Rgft3mQ and manually fix the failures, or you can also type `pre-commit.ci autofix` on its own in a comment and the bot will try to fix it for you (you'd then want to pull the changes locally). 

**new test**: I did checkout your branch locally to make sure it works (and it does!) but when adding new features we also need to add to the automated test suite. So this PR will need a new test in `src/yt_napari/_tests/test_widget_reader.py`. Adding tests for widget features can be a little tricky -- but you should be able to follow how the other tests are written to write a new one. In this case, I think the easiest route would be to monkeypatch the `QFileDialog` `exec_()` and `selectedFiles()` functions (see [this link](https://docs.pytest.org/en/7.1.x/how-to/monkeypatch.html) for how to monkeypatch with pytest).

2023-11-10 16:19 UTC, chrishavlin commented on src/yt_napari/_widget_reader.py
> +            "$schema": "https://yt-napari.readthedocs.io/en/latest/_static/yt-napari_latest.json",
Same change here:
```suggestion
            "$schema": schema_name,
```

2023-11-16 10:12 UTC, TomasPetro commented
@chrishavlin 
So I installed tox but I'm currently having trouble running it. Tried to run it in different folders but it keeps throwing an error. Mostly similar. Are there other ways to run the tests or am I getting an error somewhere when running it? 
![image](https://github.com/data-exp-lab/yt-napari/assets/115801572/f619ad62-0e5f-44d8-ab0d-5f69c9dfb9de)

2023-11-16 16:06 UTC, chrishavlin commented
Oh, sorry, I must have some docs out of date. I don't really use tox anymore with `yt-napari` -- I just run `pytest -v .` to run the tests in my current environment and then rely on the github CI to make sure it passes with other systems and python versions.

2023-11-17 09:34 UTC, TomasPetro commented
Previously I tried pytest but i got there problem with qtbot. And even in those tests I didn't touch. In total I get 12 such errors. Do you know of any solution to this problem ? 
![image](https://github.com/data-exp-lab/yt-napari/assets/115801572/3bb99772-a78f-4eb4-bc18-cde0064c764a)

2023-11-17 16:51 UTC, chrishavlin commented
you'll need the `pytest-qt` plugin as well, `pip install pytest-qt`

2023-11-23 23:16 UTC, TomasPetro commented
Hi. 
I'm currently working on tests but I've been troubleshooting the QfileDialog window that pops up when I save a json file for a few days.
 I've tried qtbot etc but it didn't help and I still need to manually type the filename and then save. Do you know of any suitable implementation I could try ? 
![image](https://github.com/data-exp-lab/yt-napari/assets/115801572/a37d092d-77aa-4986-a13a-64f48993d622)

2023-11-24 16:12 UTC, chrishavlin commented
I think the easiest approach will be to monkeypatch within pytest it so that you don't have to deal with the popup, see my comment up higher:

> In this case, I think the easiest route would be to monkeypatch the QFileDialog exec_() and selectedFiles() functions (see [this link](https://docs.pytest.org/en/7.1.x/how-to/monkeypatch.html) for how to monkeypatch with pytest).

So you should be able to write a test that provides string inputs to provide a temporary filename and avoid the pop-up entirely.

2023-11-29 18:40 UTC, TomasPetro commented
pre-commit.ci autofix

2023-11-29 18:54 UTC, TomasPetro commented
Hi, so I wrote the tests. Will you take a look at it ?  Currently it doesn't pass only codecs/patches but I didn't do anything with those functions on those lines.

2023-11-29 19:26 UTC, chrishavlin commented
Great! Thanks @TomasPetro ! I should be able to look later today or tomorrow.

2023-11-30 20:11 UTC, chrishavlin approved these changes
Looks great, thanks @TomasPetro ! I'll push up some changes to fix the coverage issues (as well as another couple small changes to the tests) and then this should be ready to merge.

2023-11-30 20:35 UTC, merged

2023-12-01 20:06 UTC, TomasPetro commented
Nice :)